services:
  - type: web
    name: intent-based-chatbot
    runtime: python
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python flaskchatbot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
