services:
  - type: web
    name: intent-based-chatbot
    env: python
    runtime: python-3.12.4
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flaskchatbot:app